### ISSUE TITLE
Write.py doesnt work

### ISSUE THREAD

**Issue by CrafterRa** [alex-suspicious/OctoTex#39]
Shows this error

Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\GarrysModRTX\OctoTex-main\write.py", line 257, in <module>
    saveAllTextures(mod_dir, replacements_file)
  File "D:\SteamLibrary\steamapps\common\GarrysModRTX\OctoTex-main\write.py", line 177, in saveAllTextures
    f = open(f"materials/{x.replace('.png','.mat')}","r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'materials/02982B018AFB7CD2.mat'

have no idea why

**Comment by CrafterRa** [comment]
webui works but is insanely slow is that normal?
